# Generated by Django 4.1.7 on 2023-03-31 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MedTest_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_scheduled",),
    ]
