# Generated by Django 4.1.7 on 2023-04-01 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("MedTest_auth", "0002_remove_user_is_scheduled"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "college_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("college_title", models.CharField(max_length=30, unique=True)),
            ],
            options={"verbose_name_plural": "Colleges", "db_table": "College",},
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "dept_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("dept_title", models.CharField(max_length=30, unique=True)),
            ],
            options={"verbose_name_plural": "Departments", "db_table": "Department",},
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programme_title", models.CharField(max_length=30, unique=True)),
                (
                    "programme_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={"verbose_name_plural": "Programmes", "db_table": "Programme",},
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_title", models.CharField(max_length=9, unique=True)),
                (
                    "session_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={"verbose_name_plural": "Sessions", "db_table": "Session",},
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "stud_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MedTest_auth.college",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MedTest_auth.department",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MedTest_auth.programme",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MedTest_auth.session",
                    ),
                ),
                (
                    "user_id",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Student Profile",
                "db_table": "Student Profile",
            },
        ),
    ]
