# Generated by Django 4.1.7 on 2023-04-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedTest_auth", "0003_college_department_programme_session_studentprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="college_description",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
