# Generated by Django 4.1.7 on 2023-04-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedTest_auth", "0004_college_college_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="programme_title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
