# Generated by Django 4.1.7 on 2023-04-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MedTest_auth", "0005_alter_programme_programme_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="studentprofile", name="department",),
    ]
