# Generated by Django 4.1.7 on 2023-04-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MedTest_auth", "0008_programme_studentprofile_programme"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, unique=True)),
            ],
            options={"verbose_name_plural": "Gender", "db_table": "Gender",},
        ),
        migrations.RemoveField(model_name="studentprofile", name="programme",),
        migrations.AddField(
            model_name="studentprofile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="department",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="MedTest_auth.department",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(name="Programme",),
    ]
