# Generated by Django 4.1.7 on 2023-04-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MedTest_auth", "0009_gender_remove_studentprofile_programme_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MedTest_auth.gender",
            ),
        ),
    ]
