# Generated by Django 4.1.7 on 2023-04-02 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MedTest_auth", "0010_alter_studentprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MedTest_auth.department",
            ),
        ),
    ]
