# Generated by Django 4.1.7 on 2023-04-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MedTest_auth", "0011_alter_studentprofile_department"),
    ]

    operations = [
        migrations.RemoveField(model_name="scheduletest", name="has_expired",),
    ]
