# Generated by Django 4.1.7 on 2023-04-03 19:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("MedTest_auth", "0012_remove_scheduletest_has_expired"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_type", models.CharField(max_length=30)),
            ],
            options={"verbose_name_plural": "Blood Group", "db_table": "Blood Group",},
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "result_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("HB", models.IntegerField()),
                ("MP", models.CharField(max_length=30)),
                ("DIFF", models.CharField(max_length=30)),
                ("SNIP", models.CharField(max_length=30)),
                ("GENOTYPE", models.CharField(max_length=30)),
                ("SAG", models.CharField(max_length=30)),
                ("PREGNANCY", models.CharField(max_length=30)),
                ("REACTION", models.CharField(max_length=30)),
                ("PROTEIN", models.CharField(max_length=30)),
                ("SUGAR", models.CharField(max_length=30)),
                ("BILIRUBIN", models.CharField(max_length=30)),
                ("ACETONE", models.CharField(max_length=30)),
                ("GRAVITY", models.CharField(max_length=30)),
                ("U_PREGNANCY", models.CharField(max_length=30)),
                ("MICROSCOPY", models.CharField(max_length=30)),
                ("date_created", models.DateTimeField(auto_now=True)),
                (
                    "GROUPING",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MedTest_auth.bloodgroup",
                    ),
                ),
                (
                    "stud_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MedTest_auth.studentprofile",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Test Result", "db_table": "Test Result",},
        ),
    ]
