# Generated by Django 4.1.7 on 2023-04-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedTest_auth", "0013_bloodgroup_testresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult", name="HB", field=models.FloatField(),
        ),
    ]
