# Generated by Django 4.1.7 on 2023-04-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedTest_auth", "0014_alter_testresult_hb"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="SICKLING",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
