# Generated by Django 4.1.7 on 2023-04-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedTest_auth", "0015_testresult_sickling"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sickling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sick", models.CharField(max_length=30)),
            ],
            options={"verbose_name_plural": "Sickling", "db_table": "Sickling",},
        ),
    ]
