# Generated by Django 4.1.7 on 2023-04-04 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MedTest_auth", "0018_alter_testresult_stud_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult",
            name="SICKLING",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MedTest_auth.sickling",
            ),
        ),
    ]
